"""create activation_tokens table

Revision ID: c3013042c6b1
Revises: 
Create Date: 2026-01-12 17:23:35.339035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3013042c6b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=6), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_tokens_id'), 'activation_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_activation_tokens_token'), 'activation_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_activation_tokens_user_id'), 'activation_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_tokens_user_id'), table_name='activation_tokens')
    op.drop_index(op.f('ix_activation_tokens_token'), table_name='activation_tokens')
    op.drop_index(op.f('ix_activation_tokens_id'), table_name='activation_tokens')
    op.drop_table('activation_tokens')
    # ### end Alembic commands ###